### ISSUE TITLE
Module depends on availability of Weasel::Driver::Selenium2

### ISSUE THREAD

**Issue by jame** [perl-weasel/pherkin-extension-weasel#4]
in the module Synopsis, Weasel::Driver::Selenium2 is listed as a driver.  It is my understanding that there are no other drivers that will work with this module, so some kind of dependency should be listed in Makefile.PL for it.

**Comment by ehuelsmann** [comment]
Added to Weasel as a runtime recommended module (and as before, this one depends on Weasel).
